

export const SUPPORTED_KEYS = {
  null: 'NULL',
  cancel: 'CANCEL',
  help: 'HELP',
  back_space: 'BACK_SPACE',
  tab: 'TAB',
  clear: 'CLEAR',
  return: 'RETURN',
  enter: 'ENTER',
  shift: 'SHIFT',
  control: 'CONTROL',
  alt: 'ALT',
  pause: 'PAUSE',
  escape: 'ESCAPE',
  space: 'SPACE',
  page_up: 'PAGE_UP',
  page_down: 'PAGE_DOWN',
  end: 'END',
  home: 'HOME',
  arrow_left: 'ARROW_LEFT',
  left: 'LEFT',
  arrow_up: 'ARROW_UP',
  up: 'UP',
  arrow_right: 'ARROW_RIGHT',
  right: 'RIGHT',
  arrow_down: 'ARROW_DOWN',
  down: 'DOWN',
  insert: 'INSERT',
  delete: 'DELETE',
  semicolon: 'SEMICOLON',
  equals: 'EQUALS',

  numpad0: 'NUMPAD0',
  numpad1: 'NUMPAD1',
  numpad2: 'NUMPAD2',
  numpad3: 'NUMPAD3',
  numpad4: 'NUMPAD4',
  numpad5: 'NUMPAD5',
  numpad6: 'NUMPAD6',
  numpad7: 'NUMPAD7',
  numpad8: 'NUMPAD8',
  numpad9: 'NUMPAD9',
  multiply: 'MULTIPLY',
  add: 'ADD',
  separator: 'SEPARATOR',
  subtract: 'SUBTRACT',
  decimal: 'DECIMAL',
  divide: 'DIVIDE',

  f1: 'F1',
  f2: 'F2',
  f3: 'F3',
  f4: 'F4',
  f5: 'F5',
  f6: 'F6',
  f7: 'F7',
  f8: 'F8',
  f9: 'F9',
  f10: 'F10',
  f11: 'F11',
  f12: 'F12',

  command: 'COMMAND',
  meta: 'META',
} as const

export const DEFAULT_OUTPUT_FOLDER = 'wdio'
export const KEY_NOT_SUPPORTED_ERROR = `key "%s" not supported (supported are ${Object.keys(SUPPORTED_KEYS).join(', ')}), please file an issue in https://github.com/webdriverio/chrome-recorder to let us know, so we can add support.`
