name: Build tool and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-tool-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run Tests
        run: npm run test
